site_name: Introduction to cellular biology
site_url: https://anaraquelpengelly.github.io/cell_biology_intro/
site_description: >
  Introduction to Cell Biology lecture
repo_url: https://github.com/Anaraquelpengelly/cell_biology_intro.git

nav:
  - Home: index.md
  - Slides: pitch.md
  - References: refs.md

theme:
  name: material
  custom_dir: theme
  palette:
    primary: black
    accent: red
  feature:
    tabs: true

reveal:
  path: reveal.js/dist
  transition: slide
  theme:
    name: white.css
    path: theme
  plugin:
    path: reveal.js/plugin

extra:
  author:
    name: fhiegel

# Extensions
#plugins:
 # - search
  #- print-site

markdown_extensions:
  - admonition
  - extra
  - meta
  - tables
  - toc
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.smartsymbols
  - pymdownx.tabbed
  - pymdownx.tasklist
